### ISSUE TITLE
lage map.html

### ISSUE THREAD

**Issue by ezizomer99** [3Beast/o-tivity#18]

**Comment by TonjeFM** [comment]
Får bare til å legge til marker på det siste eventet som vi legger til selv. 
Så når dere tester ut, bruk en virkelig/ekte adresse.

**Comment by TonjeFM** [comment]
Kartet fungerer bare hvis det ligger et event i localstorage

**Comment by TonjeFM** [comment]
> Kartet fungerer bare hvis det ligger et event i localstorage. Prøver å fikse det nå

FIKSET!
